server:
  port: 7777

spring:
  activemq:
    broker-url: tcp://192.168.1.9:61616 #用自己本机的IP地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: false       #false=Queue  true=Topic

#自己定义队列名称
myQueueName: springboot-activemq-queue
